spring:
  application:
    name: demo
  datasource:
    url: jdbc:oracle:thin:@115.90.212.20:10000:XE
    username: 123
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

server:
  port: 80
